#!/usr/bin/env python3
import sys, os
direc = sys.argv[1]
nombre = os.path.basename(direc)
carpeta = nombre[0:len(nombre) - 4]
os.system('unsquashfs %s' % nombre)
os.rename('squashfs-root', carpeta)

